# Generated by Django 5.0.2 on 2024-05-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpgl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libele', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Bibliotheque',
                'verbose_name_plural': 'Bibliotheques',
            },
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'Eleve', 'verbose_name_plural': 'Eleves'},
        ),
        migrations.AlterModelOptions(
            name='livre',
            options={'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AlterField(
            model_name='eleve',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lpgl.eleve', verbose_name='Eleve'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='quantite',
            field=models.IntegerField(default=1, verbose_name='quantite'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=100, unique=True, verbose_name='titre'),
        ),
    ]
